### PR TITLE
Client stays now connected

### PR DESCRIPTION
**Pull request by mineiwik**

### CODE REVIEW

**Review by siku2 — APPROVED** [review]

**Comment by siku2** [comment]
ehhh, this doesn't actually do anything xD

**Comment by mineiwik** [comment]
but for some reason the Godot client does not disconnect anymore (at least on macOS...)

**Comment by siku2** [comment]
as you might expect, the server claims that the client is at fault

**Comment by siku2** [comment]
or maybe it's fastapi closing the connection as soon as the handler returns...

**Comment by siku2** [comment]
welp, apparently that's actually the case... My beautiful unit tests couldn't catch that because it's handled by uvicorn.

**Pull request merged**
